version: '3.8'

services:
  tendermint-chain0:
    container_name: tendermint-chain
    image: tendermint/tendermint:v0.34.19 #v0.35.7
    ports:
      - 26656:26656
      - 26657:26657
      - 26660:26660
    volumes:
      - ./tendermint:/tendermint
